// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqyqegtuurhybxlftnas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxeXFlZ3R1dXJoeWJ4bGZ0bmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjY0NzcsImV4cCI6MjA2MDgwMjQ3N30.cVLQSO4I2BjmkSfeAJNv8Uu1Ts3L8TfHIAe-qy1KLdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);